### ISSUE TITLE
Usage of Noblox.js

### ISSUE THREAD

**Issue by VoiditeDev** [Wayyllon/RobloxGroupAutoKick#1]
ok, this relies on `requests` which is unefficient, I do recommend using [noblox.js](https://noblox.js.org/) to make it easier for the code to be understandable

I even suggested it in the developer forums
https://devforum.roblox.com/t/ban-users-from-groups/2541610/3?u=vscplays

**Comment by maxhithere** [comment]
and why is requests inefficient? you do realize that noblox.js is just a wrapper for the actual roblox api to combine functions in one, it's not faster or slower the just using your standard request library. 

also this makes no sense, as the code is in python and noblox is written in javascript...

**Comment by VoiditeDev** [comment]
im so dumb, will close this
